### ISSUE TITLE
What do you think about Este.js

### ISSUE THREAD

**Issue by olso** [sindresorhus/ama#100]
hello :smile: everything is explained in readme.md https://github.com/este/este

**Comment by sindresorhus** [comment]
The [last time](https://github.com/tastejs/todomvc/issues/647) I looked at Este.js it was a MVC framework on top of Google Closure Tools. Seems it has pivoted a good bit since then, and from the looks of it, for the better.

Can't really give a useful opinion about it without actually trying it out, but there's a lot to like in the readme (React, Flux, immutability, ES2015, etc). It would definitely be on the list of stacks to consider for my next front-end project.
