### ISSUE TITLE
What Slack channels do you participate in and what channels would you suggest a dev be part of?

### ISSUE THREAD

**Issue by weblancaster** [sindresorhus/ama#135]

**Comment by sindresorhus** [comment]
I really don't get the Slack hype. I've used it for a while and it's ok, but that's it. I would probably use it internally with a team, but definitely not for public discussions.

**[Slack is emphatically not for societies](https://news.ycombinator.com/item?id=9754626)**

Because of the hype, lots of communities are trying to use it for something it wasn't made for. We already have IRC, [Gitter](https://gitter.im), and other services for this. It's awkward how every Slack team needs a "separate account" (though they can be connected) and you can only be in one Slack team at once. That makes it really hard to participate in multiple communities at once, which is a common need.

So to answer your questions. I've been participating in https://atomio.slack.com, but won't continue, and have no channels to recommend.

**Comment by weblancaster** [comment]
Thanks,
