### ISSUE TITLE
What are your photography preferences?

### ISSUE THREAD

**Issue by Flet** [sindresorhus/ama#149]
I noticed you've mentioned photography in a few answers and showed some rad pet photos in #2.

What do you enjoy photographing?

What gear do you have/prefer for photography?

Do you have a preferred workflow for processing digital photographs?

Do you share your photographs online?

**Comment by sindresorhus** [comment]
My favorite categories are landscape, animals and action photography, but I do a bit of everything really. My current goal is to get better at portraits, which I find hard to do properly. I really enjoy it when I'm able to bring out some emotion or atmosphere in my photos.

I have a [Nikon D610](http://www.nikonusa.com/en/Nikon-Products/Product/dslr-cameras/1540/D610.html) with [Nikon 18-300mm](http://www.nikonusa.com/en/Nikon-Products/Product/Camera-Lenses/AF-S-DX-NIKKOR-18-300mm-f%252F3.5-5.6G-ED-VR.html) and [85mm f/1.8](http://www.kenrockwell.com/canon/lenses/85mm.htm) lenses. The 18-300mm is a great all-around lens for travelling, and the 85mm is a classic with superb quality for its relatively low price. I do sometimes miss the [70-200mm f/2.8](http://www.usa.canon.com/cusa/consumer/products/cameras/ef_lens_lineup/ef_70_200mm_f_2_8l_is_ii_usm) which I used [at work](https://github.com/sindresorhus/ama/issues/107). It's the best lens I've ever used. I also have an iPhone 6 which has a surprisingly good camera. I've used it a lot lately instead of the Nikon as it's easier to carry around.

Until recently, I used [Aperture](https://en.wikipedia.org/wiki/Aperture_(software)) for all my organizing and editing, but I switched to [Photos](https://www.apple.com/osx/photos/) when it was launched. It doesn't have a lot of advanced editing features, but I realized I don't do a lot of that these days anyways. I also have Lightroom for those occasions when I do need something more. I like my photos authentic so I try not edit them too much, except for the stuff I post on Instagram of course. Some things I've found can really make a portrait shine is to reduce shadow, turn up the definition a little bit and brighten/sharpen the eyes, and add a tiny bit of vignette.

I don't really share a lot of photos. Most are just locked up in my computer.

You can find some here:
https://500px.com/sindresorhus
https://instagram.com/sindresorhus/
