### ISSUE TITLE
What will you be doing next years?

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#178]
Right now you're mainly building node modules, yeoman, grunt plugins, ...

What will you be doing in the future?

**Comment by sindresorhus** [comment]
Well, the future is now, since I'm answering this 4 years late. A couple of years ago, I learned Swift and macOS development, so that has been a big focus in addition to my forever growing open source responsibilities. In the past year, I have also learned TypeScript and started using it for some projects. I like its potential, but it still feels too immature for me to invest all my energy into. One major thing that has changed me as a programmer in the last years is that I've fallen in love with types. Previous me would have said it's not worth the effort and that it's too verbose and complicated, but the more experienced me has discovered how much it helps readability and maintainability of code, and even reduces bugs. Swift has been the biggest cause of this discovery. I feel like learning Swift has also made me a better JavaScript developer. I taught me new patterns and helped me write more readable code ([no more abbreviations!](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/prevent-abbreviations.md)).

My next goal is still to learn Rust, but I don't think I'll have time for that in the coming year, aside from toying with it. There's just too much to do in open source for JavaScript and Swift.

I'm still doing open source full-time and I plan to do so as long as I can. Hopefully, for many years to come.
