### ISSUE TITLE
Why don't you capitalize the readme filename in your repositories?

### ISSUE THREAD

**Issue by 0xffff0000** [sindresorhus/ama#197]

**Comment by sindresorhus** [comment]
Aesthetics. It looks better lowercased.

**Comment by fvgs** [comment]
> And there's no longer any practical reason to uppercase it

I arrived at the same conclusion regarding aesthetics when considering the presentational merits of all-uppercase vs. first-letter-uppercase vs. all-lowercase. However, I find the practical reason for uppercasing at least the first letter of meta files (e.g. readme, license, contributing) is so when the files are listed in a terminal or GitHub, the meta files will be listed before non-meta files (package.json, yarn.lock, other config files, etc.). Thus, they end up partitioned, which imo enhances the presentation and ease with which one can scan the contents of the repo. That's why I uppercase mine.

I pose the following question dialectically: Do you not consider the above reason to have sufficient practical merit, or is there instead a nuance I'm not considering?

**Comment by sindresorhus** [comment]
Sure, you get them listed first on GitHub, but they also steal all the attention because of being all uppercase, when most of them are not important. This also only solves the problem for your own repos. Instead, I just made a [Chrome extension that hides unimportant files](https://github.com/sindresorhus/hide-files-on-github). (It says it's for dotfiles, but I use it for many other files too). Here's the regex I use: `^\.|^license|^appveyor\.yml$|^yarn\.lock$|^screenshot(?:-\w)*\.png$|^circle\.yml$|^codecov\.yml$|^contributing\.md$|\.sublime-project$|^lerna\.json$|^gulpfile\.js$|^makefile$`

**Comment by Rafi993** [comment]
https://softwareengineering.stackexchange.com/a/301708
