### ISSUE TITLE
What is your system for reaching inbox zero?

### ISSUE THREAD

**Issue by Whoaa512** [sindresorhus/ama#201]
per sindresorhus/todo#3

**Comment by sindresorhus** [comment]
I started using [Mailbox](http://www.mailboxapp.com/) on my phone to triage emails. Previously I got overwhelmed by the mass amount of emails, but now I snooze them to times when I think I will be able to handle them. So "inbox zero" might be a lie. Especially useful since a lot of emails are implicit todo items. I plan to switch to [Google Inbox](http://www.google.com/inbox/) though, as Mailbox crashes all the time on my iPhone and haven't seen much change since it was initially relased.

As for the emails themselves I try not to procastinate too much. Emails that doesn't require a lot of thinking/writing, I try to answer right away. In the end, I do spend a lot of time answering emails as I strive to answer them all.

**Comment by RichardLitt** [comment]
Mailbox has a desktop app now, too.

**Comment by seriema** [comment]
> It’s with heavy hearts that we let you know we’ll be shutting down Mailbox on February 26, 2016.
https://www.mailboxapp.com

@sindresorhus did you ever make the switch to Google Inbox? If so, did your way of handling emails change?

**Comment by sindresorhus** [comment]
Yes, a long time ago. Glad I did it. Google Inbox is so much better. The bundles in Inbox is very useful for managing which emails to focus on. The snooze functionality is a lot better. Generally it's just better. Try it.

**Comment by RichardLitt** [comment]
What're you going to use now that Mailbox is going away, on your phone? I haven't decided yet.

**Comment by sindresorhus** [comment]
Google Inbox.
