### ISSUE TITLE
Do you receive job offers from competitive companies?

### ISSUE THREAD

**Issue by lborgav** [sindresorhus/ama#203]
Do you receive job offers from competitive companies like Google, Facebook, Quora? 
How often? 
Have you already declined an "amazing offer"?
Would you accept?

**Comment by sindresorhus** [comment]
> Do you receive job offers from competitive companies like Google, Facebook, Quora?

Yes.

> How often?

Not that often anymore since I've declined so many times and clearly state in my GitHub profile I'm not available for hire.

> Have you already declined an "amazing offer"?

Haven't gotten an "amazing offer".

> Would you accept?

Probably not. I'm not interested in working for a large company. I'm allergic to bureaucracy and meetings, and don't care about money, so they don't have much to offer me. I never say never though. So maybe if the right challenge came along.
