### ISSUE TITLE
What do you think about the new Apple products?

### ISSUE THREAD

**Issue by robbbz** [sindresorhus/ama#230]

**Comment by sindresorhus** [comment]
*Disclaimer: I'm a big fan of Apple products for their superb quality, great UX, and attention to detail.*

iPad Pro has a beautiful screen, but it's not something I would want. Even with the split-screen functionality in iOS 9, the iPad is still a consumption device in my mind, not a productivity one. Impressive regardless.

I was positively surprised when they announced the 3D Touch functionality in iPhone 6S. They invented a new gesture that's going to be immensely useful. The new camera also looks like an excellent improvement. However, I have an iPhone 6, so I'm going to wait for the iPhone 7 (Can't buy a new iPhone every year...), but this one almost got me buying.

The AppleTV announcement was probably the most exciting. Even though the new one isn't as revolutionary as we've hoped, I think the App Store part of it is a great move. Especially since it's very easy for developers to port their apps/games over. I can see AppleTV being a real console contender in the future. They only need to release a good gamepad. The new UI is also a great improvement. The old one was just horrific.

-

What I really want though, is a new MacBook Pro 15" with an improved design and the new Intel Skylake processor!!
