### ISSUE TITLE
What does "at least one javascript framework" really mean in the job description?

### ISSUE THREAD

**Issue by artych** [sindresorhus/ama#232]
There are many jobs with a such requirement "... good knowledge of at least one framework, i.e.: AngularJS, Ember.js, Backbone.js".

I personally know ember, and I'd like to develop ember-cli apps. What should I expect from such a job? I see many options:
- Company is large, there are many projects for every javascript framework. (But why not to choose the best one ?)
- If you know at least one of them, you will quickly learn others. (I think you'll need 1-2 month to learn ember (on ember-cli with ember-data) and produce production-ready code and tests, because of many gotchas. And also will company wait till I learn AngularJS and Backbone.js?)
- We really work with AngularJS only, but we like to collect front-end developers CVs.

Thank you for answer!

**Comment by es128** [comment]
I know this is Sindre's AMA, but since he's already described how he's not actively in the job market I figured I'd provide an answer since I have a perspective on this.

In my experience it's mostly the second one. Believe it or not there are a whole lot of web dev candidates out there who have never worked with a major framework - perhaps they've used jquery only or otherwise just generally have very outdated skills. Sometimes they've stayed in the same job for a long time maintaining something that's years old and haven't otherwise kept up to date with the state of modern front-end engineering. 

Significant experience with any of the major frameworks is an indicator that the candidate has worked on substantial projects that followed some sort of structural pattern, which will be reasonably translatable to whatever the company happens to be using - or the framework-du-jour down the road. It shouldn't take 1-2 months for such a candidate to get going, and it's ok if they bump into some of the gotchas and learn more of the fine-grain details along the way on the job. Plus there's likely other experts on the team that can help the newbie avoid pitfalls.

Your third bullet is somewhat applicable as well - the candidate with deep experience using the same framework the company/team is using has an edge over others. But it's too limiting to just list one; hiring managers want to make sure they have a decent pool of candidates to choose from.

**Comment by artych** [comment]
Thanks, @es128 !

**Comment by sindresorhus** [comment]
:+1:
