### ISSUE TITLE
What's your ES6 (ES2015) config like?

### ISSUE THREAD

**Issue by alebelcor** [sindresorhus/ama#250]
I see you recently started writing in ES6 (ES2015).

Are you transpiling your code to ES5 or just using Node 4+?

P.S. Thanks for your code! lots of inspiration to draw from.

**Comment by sindresorhus** [comment]
For CLI tools, I'm now starting to target latest Node.js (meaning ES2015 goodies!). Since this is something users install directly on their own system I feel I can force a recent Node.js version. Reusable modules, however, will stay with Node.js 0.10 compatibility out the [LTS period](https://github.com/nodejs/LTS/#lts-plan). I use [Babel](https://babeljs.io/) for apps and some larger modules, like [Pageres](https://github.com/sindresorhus/pageres/pull/212). I write all my tests in ES2015++ (async/await ftw!) since [AVA](https://github.com/sindresorhus/ava) comes with it builtin using the Babel require hook. [Example](https://github.com/sindresorhus/temp-write/blob/66fcc89c8124ce0eabde8b3c14c384e018646fba/test.js).
