### ISSUE TITLE
Is this shit your job?

### ISSUE THREAD

**Issue by jariz** [sindresorhus/ama#253]
Joking aside, how do you find so much time to put into open source?

**Comment by es128** [comment]
beat ya to it, buddy

#14

**Comment by jariz** [comment]
Ha, thanks. so I guess it is his job. (sorta)

**Comment by sindresorhus** [comment]
No, I just enjoy it a lot. I don't find time for open source, I make time. It's all about prioritization. Instead of watching TV, surfing Reddit, etc, I do open source. I don't currently [work](https://github.com/sindresorhus/ama/issues/14) right now as I'm [traveling](https://github.com/sindresorhus/ama/issues/56), but I actually did even more open source in my free time when I did work.
