### ISSUE TITLE
Why promise instead of callback?

### ISSUE THREAD

**Issue by stevemao** [sindresorhus/ama#257]

**Comment by cht8687** [comment]
You should ask why ES6 is better than ES5 @stevemao

**Comment by unixzii** [comment]
In **Node.js**, I think writing callback trap is super suck thing.Whatever operation you perform maybe async in **Node.js**, such as `fs.readdir`, `fs.stat`. With Promise, at least, the writing style is more readable for us human as a flow. Moreover, it's not very difficult to do, cuz there are many Promise libraries like **Q**, **then.js**.

**Comment by sindresorhus** [comment]
It makes code simpler and more readable, less argument shifting for optional options object (since there's no `cb` argument anymore), easier to [share code between sync and async APIs](https://github.com/sindresorhus/write-json-file/blob/883f6a81f81bc6fa3b99ef632b7f8d66b2bfc496/index.js#L26-L27) (because both return something, either value or promise), but most importantly because we finally have a native async primitive and it will just work with [async function (async/await)](http://www.sitepoint.com/simplifying-asynchronous-coding-es7-async-functions/), which is amazing. [This](https://github.com/sindresorhus/got/blob/3a5a80ec9b33ffaabc31ba90b00a5e48ee0690a8/test/http.js#L41) is a lot nicer than nested callbacks.
