### ISSUE TITLE
How do you feel about the universe possibly being a computer simulation?

### ISSUE THREAD

**Issue by HugoGiraudel** [sindresorhus/ama#261]

**Comment by sindresorhus** [comment]
While I enjoy movies with that theme, like The Matrix, I'm gonna go with [Occam's razor](https://simple.wikipedia.org/wiki/Occam%27s_razor) when it comes to [simulation hypothesis](https://en.wikipedia.org/wiki/Simulation_hypothesis) - The simplest explanation is usually the correct one. Numerous of these hypothesises see the universe as they wish it to be, rather than as it probably is - A random fathomless in which we're just transient fortuitous participants.
