### ISSUE TITLE
Are you satisfied with your AMA?

### ISSUE THREAD

**Issue by eush77** [sindresorhus/ama#270]
What type of questions do you like and what do you not like?

Did you wish for something better / different when you created your AMA than what it turned out to be?

**Comment by sindresorhus** [comment]
I am. It's a bit overwhelming to be honest. I would never have imagined I would receive so many great questions. Now I just have the self-imposed pressure of answering them all in a timely manner.

> What type of questions do you like and what do you not like?

I enjoy questions that forces me to truly think and reflect. I don't like presumptive questions.

> Did you wish for something better / different when you created your AMA than what it turned out to be?

Turns out answering questions takes a lot longer than I thought. I wish I had more time to elaborate and perfect the answers. I'm planning on turning some answers into blog posts and make them more comprehensive, though.
