### ISSUE TITLE
Were there bash commands that destroyed your life?

### ISSUE THREAD

**Issue by vdemedes** [sindresorhus/ama#292]
Well, I over-dramatized a bit, but only to highlight the point. Perhaps something like `rm -rf /`?

**Comment by sindresorhus** [comment]
Once upon a time in the 90s, I managed to destroy my computer by issuing a `del` command, I think, on my Windows desktop. I had no idea what I was doing then. Also managed to corrupt the boot-sector the same year. And later corrupt the Window registry with some rouge `regedit` commands. Good times. Luckily only lost some game progress, `.txt` files with weird poems I had written, and some horrible Paint drawings. This was long before backups were mainstream.

It wasn't a command, but I did lose some precious photos when I crashed our family PC. It was running Windows 95. For some reason I had fun creating nested directories. I did it every day. Deeper and deeper. Until of course Windows couldn't handle it anymore and crashed on startup. It took my dad and my cousin's dad a whole day to debug and try to fix it. In the end they ended up having to reformatting it.

I've learned a lot since then and these days I have double backups, even triple sometimes. I have [Backblaze](https://www.backblaze.com/) backing up continuously in the background and I run Time Machine on a external harddrive once in a while. Most of my projects are also "backed up" on GitHub.
