### ISSUE TITLE
How many times have you thought about quitting open-source?

### ISSUE THREAD

**Issue by SamVerschueren** [sindresorhus/ama#305]

**Comment by sindresorhus** [comment]
I actually did. Multiple times. But it's like quitting smoking. It doesn't last very long. Was usually a few weeks, then I was back again. I guess it's more of a break, but I was sure I was quitting it for good. There's a limit of how much abuse a person can take when doing something for free. This was some years back and I didn't yet have the thick skin I have today. People were constantly being overly demanding, rude, intrusive, unreasonable, etc. One time some guy called me on my phone yelling about a bug ticket he posted half a day earlier. In the end it turned out it was his own bug.

Don't get me wrong. I'm still to this day super excited about open-source and would never have it any other way. I do wish open-source had less toxic people, though.

**Comment by SamVerschueren** [comment]
> One time some guy called me on my phone

Some people have no shame! This is really unbelievable...

> I do wish open-source had less toxic people

:+1: 

Thanks for the answer!

**Comment by stevemao** [comment]
> One time some guy called me on my phone

How'd he get your number though?

**Comment by SamVerschueren** [comment]
Via the AMA? :p

**Comment by sindresorhus** [comment]
Probably looked up my name in the Norwegian phone number database. It's all open unless you explicitly request not to be listed.
