### ISSUE TITLE
What kind of repo do you think will be more likely starred?

### ISSUE THREAD

**Issue by unixzii** [sindresorhus/ama#313]
I had worked on some repo earlier time. I don't think it's too bad, but there is a few people star them. I wanna know what kind of repo will be found and starred.

**Comment by sindresorhus** [comment]
Look at [trending repos](https://github.com/trending) to see what kind of things get popular. I've personally noticed most React related projects, like plugins, gets popular fast.

However, you shouldn't do stuff because of stars. Popularity is rarely a good metric for quality. Yes, it's cool to have a popular project, but the funnest projects I've done are not very popular, and I couldn't care less. Do it for you, not the stars.

**Comment by as1ndu** [comment]
*Well said!*
