### ISSUE TITLE
What is your favorite xkcd comic? Or share your top 5.

### ISSUE THREAD

**Issue by rheaditi** [sindresorhus/ama#420]
=)

**Comment by sindresorhus** [comment]
These are my favorites, because they're too real. In order. 


### Workflow

[![Workflow](https://cloud.githubusercontent.com/assets/170270/18305297/1e00251c-7511-11e6-8d19-05d463883e99.png)](https://xkcd.com/1172/)

### Wisdom of the Ancients

[![Wisdom of the Ancients](https://cloud.githubusercontent.com/assets/170270/18306167/cb527762-7514-11e6-8a0c-0ef8f79e49ee.png)](http://xkcd.com/979/)

### Standards

[![Standards](https://cloud.githubusercontent.com/assets/170270/18305310/2e2af3cc-7511-11e6-8d89-9a43b35b3ddf.png)](https://xkcd.com/927/)

### Duty Calls

[![Duty Calls](https://cloud.githubusercontent.com/assets/170270/18305784/4b95a766-7513-11e6-839d-3c9ba40a0a11.png)](https://xkcd.com/386/)

### Estimation

[![Estimation](https://cloud.githubusercontent.com/assets/170270/18306732/5b99eb00-7517-11e6-8225-0a1d4d38cd53.png)](http://xkcd.com/612/)
