### ISSUE TITLE
Feedback for an electron app

### ISSUE THREAD

**Issue by akashnimare** [sindresorhus/ama#422]
Hey @sindresorhus 😄 

I have built a desktop menubar app called Foco. It's like [noisli](https://www.noisli.com/) but for desktop. It would be awesome if you could try it out and give some valuable feedback.

https://github.com/akashnimare/foco

**Comment by sindresorhus** [comment]
Nice work. I tried it out on macOS.

- The app icon doesn't fit in on macOS. It should be circular or less round and tilted. The artwork in the icon is also too much out on the edge. Give it some room to breath. The artwork is also a bit cluttered. I would go for something simpler.
- The menubar icon is not retina, so it's pixelated.
- The menubar icon should not be colored and should be simpler. Also make it a `templated` image (see Electron) so it works fine in dark mode too.
- There should be a way to exit the app without having to press Cmd+Q. Usually this is done through a preferences icon that opens a menu that contains a `Quit Foco` item at the bottom.
- Drop the `X` in the popover. The popover will close when losing focus or clicking the icon again.
- The popover arrow does not match the rest of the popover.
- The popover is not round at the top, only bottom.
- Don't uppercase the different sound names.
- I would add a nice icon for each sound type. See http://noiz.io/ for how to nicely do it.
- You should disable ability to select the text and other things. `user-select: none`.
- The toggle button could use some work. I would use the light or flat one here: https://codepen.io/mallendeo/pen/eLIiG
- If I click the menubar icon many times it doesn't always toggle the popover. It works if I wait some seconds between clicking.
- The popover is placed incorrectly if the menubar is automatically hidden/shown. It's placed at the top of the screen, instead of below the menubar.
- The popover should have a pause button, so I can pause everything without having to click each toggle.

**Comment by akashnimare** [comment]
@sindresorhus thanks for the in depth feedback 🙌 . Before taking this project to ProductHunt, I'll make sure to sort out all the points you have mentioned.

**Comment by lacymorrow** [comment]
These are great tips for Electron in general!
Almost a basic checklist.
