### ISSUE TITLE
Would you make a logo for my open source project?

### ISSUE THREAD

**Issue by adnanh** [sindresorhus/ama#499]
Since you like design, would you make a logo for my open source project?
https://github.com/adnanh/webhook

**Comment by vadimdemedes** [comment]
Sindre, I have a request too! Since you like code and you even have your own test framework, would you write tests for my open source project? I don't like/want to do it myself, but it seems that you can do it with no problem. I will put your name in the readme. What do you say?

![](https://media.giphy.com/media/xUySTBqZPSeTz0JT8Y/giphy.gif)

**Comment by vadimdemedes** [comment]
Don’t you think it’s silly to expect Sindre to do free work for a project he’s not even involved in, just because he enjoys making logos for his projects? It’s like asking him to create a Node.js module for you, just because he likes code. When I say “free work”, I don’t just mean compensation, but I also mean the time he could spend on hundreds of his own projects, which require tremendous time to maintain.

**Comment by sindresorhus** [comment]
I really enjoy designing logos, and I wish I had the time to make logos for lots of open source projects. Unfortunately, I have limited time and must prioritize projects I'm passionate about. 😀

**Comment by adnanh** [comment]
> Don’t you think it’s silly to expect Sindre to do free work for a project he’s not even involved in, just because he enjoys making logos for his projects?

Never said I expect him to do it, I just asked nicely ;-)

**Comment by v-braun** [comment]
@adnanh whats wrong with your current logo? I like it :)
