### ISSUE TITLE
What do you miss most about Swift when writing JS these days?

### ISSUE THREAD

**Issue by Orangetronic** [sindresorhus/ama#509]
I enjoyed your answer to #507 and wondered if you have any thoughts on pros and cons the other way around?

Is there anything Swift has taught you that you never used to do in JS, but now you do?

**Comment by sindresorhus** [comment]
The things I miss the most are:

1. **Named parameters**
  - It makes function calls so much more readable. `create(true)` vs `create(force: true)`.
  - Yes, you can work around that by using an object, but that's more syntax noise, more annoying to type and make overloads in TypeScript, and slower.
2. **Enums**
  - I use enums a lot in Swift. It would be extremely useful in JavaScript too. For example, for APIs, you often have unique options and with JS, you have to write strings. `create('union')` vs `create(.union)`.
  - TypeScript does have some form of enum, but it's not very good.
3. **Immutability**
  - In Swift, you can just define a variable with `let` to get deep immutability for value types. In JavaScript, nothing can truly be immutable (except with a lot of usage or performance problems).
4. **Optionals**
  - In Swift, you never end up with crashes because of `null`/`undefined` (unless you force unwrap). With JS, I almost never know if a property access is going to be undefined. And in Swift, you have easy ways to unwrap.
  - JavaScript recently got `.?` and `??`, but it's far from as usable as it doesn't force unwrapping.

There are many more things like static typing (way beyond what TypeScript can provide), explicit throws, much better async (with proper cancellation), actors, protocols, generics, etc, but I don't have time to write about all of that here.
