### ISSUE TITLE
Why mix nodejs and swift? Or why not only Swift?

### ISSUE THREAD

**Issue by MW-dev** [sindresorhus/ama#538]
Hey,

why are you mixing node and swift? Wouldn't it be better if you only use Swift because it's "the Mac OS programming language"?  Or are you just using node because you know it better?

If this is the reason, why not stick to node alone? 
Where are the advantages? 
Especially talking about the cli apps.

Thanks and have a good day! :)

**Comment by sindresorhus** [comment]
I'm assuming you are referring to packages like this one: https://github.com/sindresorhus/file-icon-cli

Node.js does not always expose enough native features. The alternative would be to use a native Node.js add-on, but I don't know C++ and native add-ons come with a lot of downsides. For packages that target only macOS, it's just simpler to use Swift and execute the binary from Node.js.

Why not only use Swift? Because up until recently, it was not very convenient to make Swift command-line tools. Also, many of my command-line packages also has a normal Node.js API package. In the above case, that's https://github.com/sindresorhus/file-icon
