### ISSUE TITLE
How do you survive with all of the polar bears?

### ISSUE THREAD

**Issue by stephenplusplus** [sindresorhus/ama#55]

**Comment by passy** [comment]
Are they really fluffy?

**Comment by mathiasbynens** [comment]
My theory is that Sindre just bribes them with cokes every now and then.

![](https://cloud.githubusercontent.com/assets/81942/8472168/4234fa74-209f-11e5-993a-01d3876a466c.png)

**Comment by alrra** [comment]
The polar bear range doesn't include the part [1] of Norway where @sindresorhus lives (see [`polar bear range map`](https://upload.wikimedia.org/wikipedia/commons/2/24/Polar_bear_range_map.png)). So, the real questions are:

1)  _"How do you get along with the [elks](https://en.wikipedia.org/?title=Moose)?_
2)  _"How do you survive with all of the [lynx](https://en.wikipedia.org/wiki/Lynx)?_

--

[1] Polar bears are only present in the unincorporated area of [Svalbard](https://en.wikipedia.org/wiki/Svalbard).

**Comment by sindresorhus** [comment]
Nothing better than coming home to a loving fluffy polar bear.

![nissan-leaf_100321159_m](https://cloud.githubusercontent.com/assets/170270/8505881/69d6a498-21f7-11e5-9dc2-d0f22126260d.jpg)

**Comment by sindresorhus** [comment]
@alrra Since you asked. I do have a fun elk (although I prefer to call them moose) story:

I used to live in Lillehammer in Norway. It's 2.5 hours up north from Oslo, the capital. I lived in the forest outside the city center. One day I was walking from work to the local grocery store. I had my headphones on with some loud dubstep music. Suddenly, this huge creature ran past me. It took me some moments to realize it was a moose. It was running like crazy and were headed right towards the store. Luckily someone came out of the store right before the moose entered it, which scared the moose and made it redirect to another direction.

I managed to snap a picture of it right after it turned away from the store:

![img_2225](https://cloud.githubusercontent.com/assets/170270/8505893/4b9511bc-21f8-11e5-88f3-671701a01180.JPG)
