### ISSUE TITLE
Your favorite domains seller

### ISSUE THREAD

**Issue by MattixNow** [sindresorhus/ama#556]
Hey, I would like to buy a domain name but I do not know on which service I could buy it.

**Comment by denysdovhan** [comment]
As I remember @sindresorhus [once said](https://github.com/sindresorhus/ama/issues/476#issuecomment-310666684) he uses [Namecheap](https://www.namecheap.com/) for his domains.

@sindresorhus has anything changed since then? Have you tried ZEIT domains?

**Comment by sindresorhus** [comment]
None. They all suck... I use Namecheap for most domains as they're cheap, but their UI is just so bad. I have heard good things about ZEIT domains, but haven't tried them yet. So yeah, I would recommend ZEIT domains just because they usually make good products. I'll come back and update this answer when I have tried ZEIT domains.

**Comment by MattixNow** [comment]
Okay thanks !

**Comment by DaniGuardiola** [comment]
I have moved all my domains to Vercel (formely Zeit) because as @sindresorhus said, they all sucked. Had terrible experiences with GoDaddy, for instance. Vercel is just so clean, and fast, and easy, and powerful.
