### ISSUE TITLE
Ready for Deno?

### ISSUE THREAD

**Issue by amiteshore** [sindresorhus/ama#586]
You contributed a lot in the Node community, and we all appreciate that. Curious to know, are you planning to contribute in the new **Deno** community?

**Comment by sindresorhus** [comment]
Deno is a great project and a massive improvement over Node.js. It solves a lot of gripes I've had with Node.js since the beginning. I have high hopes for the future of Deno. However, my time is limited. I already have way too many projects to maintain, so I doubt I'll contribute much to the Deno community in the near future. I'll probably wait until it's more mature. A lot of my packages are just pure JavaScript though and should work just as well in Deno as they do in Node.js and the browser.
