### ISSUE TITLE
Why Apple?

### ISSUE THREAD

**Issue by b3u** [sindresorhus/ama#614]
I noticed that you use a Mac for programming. I never liked Apple, because of their strict policies on tinkering with their products. 

What does apple have over Windows and Linux for geeks like us?

**Comment by sindresorhus** [comment]
I use Apple products because they make (IMHO) the best hardware and software. Hardware-tinkering is indeed limited, but I don't do that anyway. As for software, there are no limitations if you [disable SIP](https://www.imore.com/how-turn-system-integrity-protection-macos).

My highly opinionated opinions:
- Windows: Good for gaming, but it generally has absolutely no taste and is held back by too much backward compatibility, legacy, and the fact that Microsoft doesn't control the hardware.
- Linux: Great for servers and has a strong core, but the current desktop options have subpar/inconsistent UI/UX and limited and low-quality third-party software.
