### ISSUE TITLE
What kind of an Internet connection do you have?

### ISSUE THREAD

**Issue by icyflame** [sindresorhus/ama#71]
Since you have mentioned that you travel a lot, and I find it hard to be connected when I travel, or am away from home. (Speed issues, seeing plaintext diffs instea of the visual github ones, etc)

Also, do you merge or view diffs on your phone? And related: what phone do you use?

**Comment by sindresorhus** [comment]
That really depends on where I am. I'm visiting my parents this summer and they have 50mbps, but when traveling it's usually a lot worse. In Singapore I had awesome speed though. At this one place, I had 1gbps! I sit a lot in coffee shops coding when traveling, and I really wish there were an app like Foursquare just for wifi speed. It's so hard to find coffee shops with even ok wifi speed. I always buy a local SIM-card when traveling, so many times it has been a lot faster to just use the 4G connection from my phone.

> Also, do you merge or view diffs on your phone?

Rarely. The GitHub mobile view isn't very good. If I do, it's mostly ones with just minor changes.

> And related: what phone do you use?

I have an iPhone 6.

**Comment by joelwallis** [comment]
@icyflame @sindresorhus I always use the CLI interface for viewing diffs, and it's definitely possible/productive because of ZSH and [oh-my-zsh framework](https://github.com/robbyrussell/oh-my-zsh). The built-in aliases and smart coloring makes it really easy to visualize changes directly from terminal. #tip

**Comment by arthurvr** [comment]
@joelwallis oh-my-zsh is slow and bloated. I'd suggest anybody not to use it. Just use vanilla ZSH or Fish and don't load hundreds of things you don't need and make your shell terribly slow.

**Comment by joelwallis** [comment]
@arthurvr I'm not sure about what you are talking about. BTW, I haven't analyzed this so far to have a so precise number of resource usage from oh-my-zsh. I have a i7 / 4GB RAM MacBook Pro, would you advise me not to use it since it doesn't even use any relevant amount of memory from my machine? Also, there are not hundreds of *things*, since [features can be enabled/disabled by using plugins](https://github.com/joelwallis/dotfiles/blob/master/.zshrc#L43).

Anyway. I'm just pointing a solution for occasions when you're offline and there's no GitHub tools available for you. Also, I really don't like to get out of terminal to check code things - like checking log, making diffs or anything else. So, it's an option, not one *"the-only-one"* solution. :)

**Comment by icyflame** [comment]
@joelwallis The CLI diff is good, but considering, that we can add line notes in GitHub only from the web interface, and you are looking at a diff to merge a PR, it is imperative that we come to the browser.

Of course, for checking particular commit diffs, and for checking logs, it makes absolutely no sense to come out of the terminal! Anyways, I asked the diff question, majorly because, @sindresorhus travels a lot, and I just want to find out how he manages to merge PR's all the time! :)
