### ISSUE TITLE
What's up with the unicorns?

### ISSUE THREAD

**Issue by silvenon** [sindresorhus/ama#8]

**Comment by sindresorhus** [comment]
I don't remember exactly. It's one of those things that just became a thing. I like unicorns because programming and OSS is hard work and having something fun and silly is important for the morale. Gifs are used for the same reason.

@addyosmani @passy @stephenplusplus Might have a better recollection.

**Comment by stephenplusplus** [comment]
I see Sindre has rare access to the official closed-source unicorn repository, which is where that canned response was first written. That confirms what we have all suspected since day one: Sindre has unicorn blood somewhere in his lineage. I only know the inside story because my best friend's cousin was adopted by the infamous John and Janice Sparkle which were the only family known (as of this time) to have given birth to a unicorn. They told me everything.

**Comment by silvenon** [comment]
It all falls into place now.
