### ISSUE TITLE
What do you think about not using semicolons in Javascript?

### ISSUE THREAD

**Issue by icyflame** [sindresorhus/ama#84]
[This](https://github.com/feross/standard) style guide recommends not using semicolons at all. But you do use semi-colons in your modules. What are your thoughts?

***

/ Although it is not you guys' AMA, would love to know about your thoughts on the matter @arthurvr @kevva @addyosmani !

**Comment by arthurvr** [comment]
> would love to know about your thoughts on the matter @arthurvr @kevva @addyosmani

I like the fact that statements are clearly separated (by semicolons). I never rely on automatic semicolon insertion.

I honestly don't really like that JavaScript even has ASI. It causes weird side effects like this:

```js
return 
  "something";

// will actually do the following
return;
  "something";
```

**Comment by kevva** [comment]
It reduces the amount of stuff you have to think about when writing code like edge cases like @arthurvr presents. I don't see the point not using them, it's easier for the author to write code and for others to read it.

In the end I guess it's just a matter of taste though. For some reason, some find them ugly.

**Comment by sindresorhus** [comment]
It's true that semi-colons can be left out in many cases. The problem is that you have to be aware of when it can't. This creates IMHO ambiguous code. I know tooling can help with this. I just prefer to keep my code strict and explicit, and optimize for readability, not typing.

In the end, semi-colons are like indentation, no actual correct answer, just strong opinions. Pick whatever you prefer and use the existing style when contributing.

**Comment by simov** [comment]
Semicolons are useless :grinning: http://eslint.org/docs/rules/semi

> On the other side of the argument are those who say ASI isn't magic, it follows a set of rules as to when semicolons are inserted and it's fairly easy to remember them. In short, as once described by Isaac Schlueter, a \n character always ends a statement (just like a semicolon) unless one of the following is true:

1. The statement has an unclosed paren, array literal, or object literal or ends in some other way that is not a valid way to end a statement. (For instance, ending with . or ,.)
2. The line is -- or ++ (in which case it will decrement/increment the next token.)
3. It is a for(), while(), do, if(), or else, and there is no {
4. The next line starts with [, (, +, *, /, -, ,, ., or some other binary operator that can only be found between two tokens in a single expression.

TBH the only real problems I have encountered by not using semicolons in my code are these two:

```js
[...].method
```

and

```js
(function () {}())
```

> Even in "never" mode, semicolons are still allowed to disambiguate statements beginning with [, (, /, +, or -:

So in those two cases I always do `;()` and `;[]` but I agree that otherwise the returned error is very weird :grinning: 

Also IMO semicolons doesn't help with readability and instead they add more noise to the code, because essentially they doesn't represent anything useful - the line is ending  anyway :)

**Comment by sindresorhus** [comment]
This is not the place to bikeshed about semicolons. I already said both side have valid points. In the end it's just a preference.
