### ISSUE TITLE
What's your take on JavaScript Standard Style and friends?

### ISSUE THREAD

**Issue by timdp** [sindresorhus/ama#96]
More precisely:

- How crucial do you consider the need for standardization in code styles?
- Do you think [Standard](https://github.com/feross/standard) (or any other style) gets it right?
- Does your boilerplate `.editorconfig` already adhere to a specific style?
- If not, have you considered switching to such a style and/or actively promoting it?

**Comment by nexdrew** [comment]
:+1: Great question(s)

**Comment by mattdesl** [comment]
👍 also curious

Seems to be a great fit for small modules. Also not sure if you are aware, but github tab rendering is not that great. 😔 

![image](https://cloud.githubusercontent.com/assets/1383811/8996363/659d5464-36e5-11e5-8a7b-08d8e9d490a0.png)

**Comment by sindresorhus** [comment]
I really wish we could have one style to rule them all. However, the JavaScript community is very diverse so I don't think we'll ever agree on *one* style. Standard style is a really awesome idea though, but it IMHO doomed itself by not adopting the most popular style (semicolons + other things). What it *does* get right is being opinionated and super easy to set up and use. No more useless code style discussions is the key here.

I just [published](https://github.com/sindresorhus/xo) my take on code style. A pragmatic alternative. I, however have no goal of it being *the* style. It's just what I personally consider the optimal style. Strict rules, tab indentation (configurable) and semicolons. If that works for you, cool. If not, just use something else, like Standard.

Relevant: https://github.com/sindresorhus/xo#why-not-standard

-

EditorConfig is for configuring editors, not code style.

**Comment by sindresorhus** [comment]
@mattdesl Looks fine to me:

![img_7549](https://cloud.githubusercontent.com/assets/170270/9023865/0f2c363c-38b0-11e5-8ed9-d3bff79f6f72.PNG)

**Comment by donaldpipowitch** [comment]
I normally like your projects, but I'm not a big friend of Xo. I know you introduced Xo with good intentions, but I'm afraid it will cause more harm than benefit. One should either accept JavaScript Standard style or not - and _not_ means use your own Linter configs (like we always did), but don't create an alternative to Standard style. Or else we will have many alternatives to Standard style and Xo soon which is equally "bad" as having Linter with presets. Even if these alternatives say they don't want to be _the_ style, people will treat it that way. (Just like in "Don't use this in production", but someone will do it anyway ;))

**Comment by kevva** [comment]
Don't use it if you don't want to. I believe @sindresorhus created this mostly for himself anyway.

**Comment by donaldpipowitch** [comment]
You're right, but I think I'm right, too. I waited for a response like this. I will not use it and I don't want to disrespect @sindresohus or his work. As I said I mostly like everything he does. I believe he want to use it mainly for himself, too, but then he shouldn't have created a nice logo, readme and several plugins around Xo. (Is he still using Grunt himself? Why does he needs a logo for himself? Sure, he wants to share and he loves what he does - which is great.) What's in the public will be used by the public. 
Xo alone will be no harm, but if many others do the same I think _that_ will be harmful as it puts us in the old problem of "everyone does its own style", but now fancy.

I would have preferred it, if he would have used a custom preset for Linters. No offense here, but in the longterm the best would have been to adopt standard style. Standard style isn't my preferred style either (I like semicolons). But Xo isn't my preferred style, too. But I will not introduce a third alternative now.

For me Standard style was the best attempt for creating, well, a standard style in years and I hope it will become more popular in the future.

**Comment by icyflame** [comment]
I agree with @kevva . Like most of the things that @sindresorhus builds, this one was for himself.

Will releasing it out in the world affect others? Maybe. I am not sure. Me personally, not really. I love the [semistandard](https://github.com/Flet/semistandard) style by @Flet . I started using it after I built some node modules and was fed-up of formatting code. So, semistandard is something that I use to ensure that all my modules have the same code style, no matter how I write code.

Once I started using it and I was sure I liked it, I installed the code-formatters out there, and built a [yeoman generator](https://github.com/icyflame/generator-nm-semistandard) that would scaffold out a project that followed semistandard by default. Did I release it out there so others could use it? No, I did it because getting something like that into the yeoman ecosystem would make my life easier, and I could simply build on top of them, and get it done without much effort.

So, I think that @sindresorhus while building xo, didn't really intend it to be used by everyone, simply to make pull requests easier. This [really long PR](https://github.com/sindresorhus/pretty-ms/pull/8#discussion-diff-32885076) in which @kevva @arthurvr and @sindresorhus were simply asking me to change the code style, could have been much shorter if only XO (or something like it had been used by @sindresorhus ).

I am not sure that there is a code formatter for xo yet. (like for [standard](https://github.com/maxogden/standard-format) and [semistandard](https://github.com/ricardofbarros/semistandard-format)) Once it comes up, it doesn't really matter how you write code, to comply with xo, you just run the formatter before committing, and that will be the end of it! :smile: That's far better than long discussions on PRs!

**Comment by sindresorhus** [comment]
![why-dont-we-have-both](https://cloud.githubusercontent.com/assets/170270/9350155/26c34ba2-4678-11e5-8a4c-45ab2c336e9e.gif)
